plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.kuwo.player'
    compileSdk 35

    defaultConfig {
        applicationId 'cn.kuwo.player'
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName '1.0-bridge'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
